# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# from turtle import goto

from PyQt5 import QtCore, QtWidgets

# from functools import partial

# from PyQt5.QtCore import QTimer, QThread, pyqtSignal



class Ui_MainWindow(object):

    def setupUi(self, MainWindow):

        import rebot_config

        def import_rebot():
            Run_.setText("正在运行")
            import rebot
            rebot.main()
            

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 669)
        centralwidget = QtWidgets.QWidget(MainWindow)
        centralwidget.setObjectName("centralwidget")
        MainWindow.setWindowTitle("欧耶v1.0.0    作者：小河灵")

        label = QtWidgets.QLabel(centralwidget)
        label.setGeometry(QtCore.QRect(20, 20, 76, 24))
        label.setTextFormat(QtCore.Qt.RichText)
        label.setObjectName("label")
        label.setText("机器人QQ：")
        # 标签：机器人QQ  

        global Rebot_QQ_Num
        Rebot_QQ_Num = QtWidgets.QLineEdit(centralwidget)
        Rebot_QQ_Num.setGeometry(QtCore.QRect(100, 20, 161, 24))
        Rebot_QQ_Num.setObjectName("Rebot_QQ_Num")
        Rebot_QQ_Num.setText(rebot_config.机器人QQ)
        # 编辑框：机器人QQ

        label_2 = QtWidgets.QLabel(centralwidget)
        label_2.setGeometry(QtCore.QRect(20, 60, 71, 24))
        label_2.setObjectName("label_2")
        label_2.setText("  QQ群:")
        # 标签：QQ群

        global Group_QQ_Num
        Group_QQ_Num = QtWidgets.QLineEdit(centralwidget)
        Group_QQ_Num.setGeometry(QtCore.QRect(100, 60, 161, 24))
        Group_QQ_Num.setObjectName("Group_QQ_Num")
        Group_QQ_Num.setText(rebot_config.QQ群号)
        # 编辑框：QQ群号

        pushButton = QtWidgets.QPushButton(centralwidget)
        pushButton.setGeometry(QtCore.QRect(20, 100, 171, 28))
        pushButton.setObjectName("pushButton")
        pushButton.setText("初始化抓取uniqueName")
        pushButton.clicked.connect(rebot_config.initialize)
        # 初始化抓取按钮

        label_3 = QtWidgets.QLabel(centralwidget)
        label_3.setGeometry(QtCore.QRect(30, 140, 186, 15))
        label_3.setTextFormat(QtCore.Qt.AutoText)
        label_3.setObjectName("label_3")
        label_3.setText("监控 uniqueName ")
        # 标签：监控 uniqueName 

        label_12 = QtWidgets.QLabel(centralwidget)
        label_12.setGeometry(QtCore.QRect(30, 160, 186, 15))
        label_12.setObjectName("label_12")
        label_12.setText("（一行一条）")
        # 标签：（一行一条）

        # label_4 = QtWidgets.QLabel(centralwidget)
        # label_4.setGeometry(QtCore.QRect(170, 140, 179, 15))
        # label_4.setObjectName("label_4")
        # label_4.setText("备注：")
        # # 标签：备注

        # label_13 = QtWidgets.QLabel(centralwidget)
        # label_13.setGeometry(QtCore.QRect(160, 160, 179, 15))
        # label_13.setObjectName("label_13")
        # label_13.setText("（仅用于记录昵称）")
        # # 标签：（仅用于记录昵称）

        global UniqueName
        UniqueName = QtWidgets.QPlainTextEdit(centralwidget)
        UniqueName.setGeometry(QtCore.QRect(20, 180, 280, 351))
        UniqueName.setObjectName("UniqueName")
        UniqueName.setPlainText(rebot_config.UniqueName_arr)
        # 多行输入框：UniqueName列表

        # global memo
        # memo = QtWidgets.QPlainTextEdit(centralwidget)
        # memo.setGeometry(QtCore.QRect(170, 180, 179, 351))
        # memo.setObjectName("memo")
        # memo.setPlainText(rebot_config.memo)
        # # 多行输入框：备注

        label_7 = QtWidgets.QLabel(centralwidget)
        label_7.setGeometry(QtCore.QRect(380, 10, 75, 47))
        label_7.setObjectName("label_7")
        label_7.setText("请求代理：")
        # 标签：请求代理

        label_5 = QtWidgets.QLabel(centralwidget)
        label_5.setGeometry(QtCore.QRect(380, 60, 71, 24))
        label_5.setObjectName("label_5")
        label_5.setText("  http：")
        # 标签：http：

        global http_
        http_ = QtWidgets.QLineEdit(centralwidget)
        http_.setGeometry(QtCore.QRect(450, 60, 311, 24))
        http_.setObjectName("http_")
        http_.setText(rebot_config.http_)
        # 输入框：http：

        label_6 = QtWidgets.QLabel(centralwidget)
        label_6.setGeometry(QtCore.QRect(380, 90, 71, 24))
        label_6.setObjectName("label_6")
        label_6.setText("  https：")
        # 标签： https：

        global https_
        https_ = QtWidgets.QLineEdit(centralwidget)
        https_.setGeometry(QtCore.QRect(450, 90, 311, 24))
        https_.setObjectName("https_")
        https_.setText(rebot_config.https_)
        # 输入框：https：

        label_8 = QtWidgets.QLabel(centralwidget)
        label_8.setGeometry(QtCore.QRect(380, 150, 75, 24))
        label_8.setObjectName("label_8")
        label_8.setText("监听地址：")
        # 标签：监听地址

        global listen_add
        listen_add = QtWidgets.QLineEdit(centralwidget)
        listen_add.setGeometry(QtCore.QRect(460, 150, 301, 24))
        listen_add.setObjectName("listen_add")
        listen_add.setText(rebot_config.listen_add)
        # 输入框：监听地址

        label_9 = QtWidgets.QLabel(centralwidget)
        label_9.setGeometry(QtCore.QRect(380, 190, 75, 24))
        label_9.setObjectName("label_9")
        label_9.setText(" Token：")
        # 标签：Token

        global Token_
        Token_ = QtWidgets.QLineEdit(centralwidget)
        Token_.setGeometry(QtCore.QRect(460, 190, 301, 24))
        Token_.setObjectName("Token_")
        Token_.setText(rebot_config.Token_)
        # 输入框：Token

        label_10 = QtWidgets.QLabel(centralwidget)
        label_10.setGeometry(QtCore.QRect(380, 230, 75, 24))
        label_10.setObjectName("label_10")
        label_10.setText("回调地址：")
        # 标签：回调地址

        global Callback_add
        Callback_add = QtWidgets.QLineEdit(centralwidget)
        Callback_add.setGeometry(QtCore.QRect(460, 230, 301, 24))
        Callback_add.setObjectName("Callback_add")
        Callback_add.setText(rebot_config.Callback_add)
        # 输入框：回调地址

        label_11 = QtWidgets.QLabel(centralwidget)
        label_11.setGeometry(QtCore.QRect(380, 270, 75, 24))
        label_11.setObjectName("label_11")
        label_11.setText("回调端口：")
        # 标签：回调端口

        global Callback_port
        Callback_port = QtWidgets.QLineEdit(centralwidget)
        Callback_port.setGeometry(QtCore.QRect(460, 270, 301, 24))
        Callback_port.setObjectName("Callback_port")
        Callback_port.setText(rebot_config.Callback_port)
        # 输入框：回调端口

        label_14 = QtWidgets.QLabel(centralwidget)
        label_14.setGeometry(QtCore.QRect(540, 310, 72, 15))
        label_14.setObjectName("label_14")
        label_14.setText("调试信息")
        # 标签：调试信息

        global Debug_info
        Debug_info = QtWidgets.QTextBrowser(centralwidget)
        Debug_info.setGeometry(QtCore.QRect(390, 340, 371, 191))
        Debug_info.setObjectName("Debug_info")
        # TextBrowser：用于输出调试信息

        Save_ = QtWidgets.QPushButton(centralwidget)
        Save_.setGeometry(QtCore.QRect(170, 570, 93, 28))
        Save_.setObjectName("Save_")
        Save_.clicked.connect(rebot_config.save_)
        Save_.setText("保存")
        # 保存按钮
        global run_
        Run_ = QtWidgets.QPushButton(centralwidget)
        Run_.setGeometry(QtCore.QRect(490, 570, 93, 28))
        Run_.setObjectName("Run_")
        Run_.setText("运行")
        Run_.clicked.connect(import_rebot)
        
        # 运行按钮


        MainWindow.setCentralWidget(centralwidget)
        menubar = QtWidgets.QMenuBar(MainWindow)
        menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        menubar.setObjectName("menubar")
        MainWindow.setMenuBar(menubar)
        statusbar = QtWidgets.QStatusBar(MainWindow)
        statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(statusbar)
        # retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

# UniqueName.setPlainText("05223D04D8C41E04\n"
# "FC5A4C4893FFECBA\n"
# "9F6BF9DEA8CD6F5E\n"
# "623AB0D6C631337D\n"
# "F4A03BC3A2C4173E\n"
# "7A1548D2E73C232B\n"
# "52EE4CEEF2334575\n"
# "38097AFE430F4C40\n"
# "AFF8D9F53C161011\n"
# "4BFFCC8C92C9CBED")
# memo.setPlainText("一只鱼啊啊啊\n"
# "币圈佐为\n"
# "北雨导演\n"
# "赚多点钱\n"
# "岐山臊子面的岐\n"
# "牧人\n"
# "麒歌CTA2号\n"
# "ZC招财进宝\n"
# "高山流水\n"
# "朱荣树")


